[theme]
primaryColor = "#A51C30"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#1E1E1E"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
